### ISSUE TITLE
Where do I download the .apk for Android?

### ISSUE THREAD

**Issue by 2011** [irislib/faq#5]
This page:

https://github.com/irislib/faq

states:

"Google Play store version and apk."

The "apk" links to:

https://github.com/irislib/iris-messenger/releases

but those releases consist of only desktop clients.

**Comment by mmalmi** [comment]
Oh, right, it's buried down there https://github.com/irislib/iris-messenger/releases/tag/jan2023

Currently adding https://iris.to to home screen is just as good, the native apps are just a wrapper for it with no added capability yet.

**Comment by 2011** [comment]
> Currently adding https://iris.to to home screen is just as good, the native apps are just a wrapper for it with no added capability yet.

Separate apps have the advantage (at the cost of additional memory usage, of course) of resistance to leaking data to other browser tabs or adding data to the browser history. After doing forensic work with browsers, I would never use a general browser for anyithing that I consider "important" (such as secure communications) without a complete profile wipe afterwards.
